Update .npmignore
inspect-js/is-typed-array pull request #52
Opened 2021-02-13 19:20 UTC by hildjj

To not include coverage output, config files, tests, and github actions.

Compressed package size goes from 8.1 kB to 4.0 kB.
Uncompressed package size goes from 36.7 kB to 10.5 kB

to check, run `npm pack --dry-run`

2021-02-13 20:09 UTC, ljharb requested changes
Package size on disk is not really important (as opposed to, say, bundle size).

Almost all of these files are extremely necessary - `npm explore is-typed-array && npm install && npm test` should always work. All of my packages always intentionally include all tests in the published package.

2021-02-13 20:09 UTC, closed without merging

2021-02-14 17:24 UTC, hildjj commented
I could imagine your wanting to ship the tests, but shipping the previous results of the tests in coverage/ and .nyc_output/ seems odd

2021-02-14 17:53 UTC, ljharb commented
That's totally fair; the coverage output should indeed be npmignored - which should have been done in 98d687a, but v1.1.4 [still has .nyc_output](https://unpkg.com/browse/is-typed-array@1.1.4/).

I've fixed that in 583076e, and will publish a release shortly with that included.

2021-02-14 18:12 UTC, hildjj commented
thanks!